const path = require("path");
const fs = require("fs-extra");
const { spawnSync } = require("child_process");
const { generateK6Script } = require("../LLMClient");
const { writeK6Handoff, mergeK6RunForMode } = require("../lib/mcpHandoff");
const { storyAppliesToAgent, collectPerformanceModesFromStories } = require("../lib/userStories");

const K6_MODES = new Set(["load", "soak", "stress", "spike"]);

function normalizeModes(modes) {
  const raw = Array.isArray(modes) && modes.length ? modes : ["load"];
  const out = [];
  for (const m of raw) {
    const s = String(m || "")
      .trim()
      .toLowerCase();
    if (K6_MODES.has(s) && !out.includes(s)) out.push(s);
  }
  return out.length ? out : ["load"];
}

function k6OnPath() {
  const r = spawnSync("which", ["k6"], { encoding: "utf-8" });
  return r.status === 0 && (r.stdout || "").trim();
}

/**
 * Writes one k6 script per mode under projectRepo (default tests/performance-testing/{mode}_test.js)
 * and handoff JSON for Cursor + k6 MCP (load, soak, stress, spike).
 */
async function runPerformanceTestAgent({ projectRepo, stories, performance = {}, output = {} }) {
  const executor = String(performance.executor || "mcp").toLowerCase();
  const scriptDirRel = (performance.scriptDirectory || "tests/performance-testing").replace(/\\/g, "/");
  const scriptDirAbs = path.join(projectRepo, scriptDirRel);
  await fs.ensureDir(scriptDirAbs);

  const fromStories = collectPerformanceModesFromStories(stories);
  const list = fromStories.length ? fromStories : normalizeModes(performance.modes);
  const baseUrl = performance.baseUrl || process.env.BASE_URL || "";
  const resolvedBaseUrl =
    (baseUrl || process.env.BASE_URL || "").trim() || "http://localhost:6061";
  const mcpRunDefaults = performance.mcpRunDefaults || { vus: 5, duration: "2m" };
  const mcpRunByMode = performance.mcpRunByMode || {};
  const k6MinScenarioDurationSeconds = performance.k6MinScenarioDurationSeconds ?? 120;

  if (fromStories.length) {
    console.log(`[perf] Modes from user story testFor: ${list.join(", ")}`);
  } else {
    console.log(
      `[perf] No load|soak|stress|spike in testFor on perf-scoped stories; using performance.modes: ${list.join(", ")}`
    );
  }
  const shouldRunK6Cli = executor === "cli" || executor === "both";

  const k6LoginEmail = String(performance.k6LoginEmail ?? "admin@admin.com");
  const k6LoginPassword = String(performance.k6LoginPassword ?? "admin");

  const k6EnvRel = `${scriptDirRel}/k6.env`.replace(/\\/g, "/");
  const k6EnvAbs = path.join(scriptDirAbs, "k6.env");
  const k6EnvBody = [
    "# Auto-generated by cs4218-ai-test-bot (performance agent). Regenerated on each `node index.js --agent=performance`.",
    "# From projectRepo, in this directory:",
    "#   set -a && . ./k6.env && set +a && k6 run ./load_test.js",
    "# Prerequisites: API must listen on the same host/port as BASE_URL (start your backend first).",
    "# Override login below or export after sourcing; values come from performance.k6LoginEmail / k6LoginPassword in agent.config.json.",
    "# If K6_WEB_DASHBOARD=true warns \"6565: address already in use\", quit other k6 runs or pick another port (see k6 docs for K6_WEB_DASHBOARD_PORT).",
    `export BASE_URL=${JSON.stringify(resolvedBaseUrl)}`,
    `export K6_LOGIN_EMAIL=${JSON.stringify(k6LoginEmail)}`,
    `export K6_LOGIN_PASSWORD=${JSON.stringify(k6LoginPassword)}`,
    ""
  ].join("\n");
  await fs.writeFile(k6EnvAbs, k6EnvBody, "utf-8");
  const outputs = [];
  const primaryScripts = [];
  let warnedK6Missing = false;

  let perfStories = stories.filter(s => storyAppliesToAgent(s, "performance"));
  if (!perfStories.length) {
    perfStories = stories;
    console.log("[perf] No stories matched testFor performance/load/k6/...; using all stories for script context.");
  }

  for (const mode of list) {
    try {
      const script = await generateK6Script(perfStories, {
        mode,
        minScenarioDurationSeconds: k6MinScenarioDurationSeconds,
        defaultBaseUrl: resolvedBaseUrl
      });
      const rel = `${scriptDirRel}/${mode}_test.js`.replace(/\\/g, "/");
      const abs = path.join(projectRepo, rel);
      await fs.writeFile(abs, script, "utf-8");
      console.log(`[perf] Wrote k6 script (${mode}): ${abs}`);
      primaryScripts.push({
        mode,
        relativePath: rel,
        absolutePath: abs
      });

      let k6Status = null;
      if (shouldRunK6Cli) {
        if (k6OnPath()) {
          const p = mergeK6RunForMode(mode, mcpRunByMode, mcpRunDefaults);
          const args = ["run"];
          if (p.iterations != null) {
            args.push(`--iterations=${Number(p.iterations)}`);
          } else {
            args.push(`--vus=${Number(p.vus)}`, `--duration=${String(p.duration)}`);
          }
          args.push(abs);
          console.log(
            `[perf] k6 CLI: ${args.join(" ")} (BASE_URL=${resolvedBaseUrl})`
          );
          const run = spawnSync("k6", args, {
            cwd: projectRepo,
            encoding: "utf-8",
            maxBuffer: 30 * 1024 * 1024,
            env: { ...process.env, BASE_URL: resolvedBaseUrl }
          });
          k6Status = run.status;
          console.log(`[perf] k6 CLI (${mode}) exit ${k6Status}\n${(run.stdout || "").slice(-3500)}`);
          if (run.stderr) console.error((run.stderr || "").slice(-1500));
        } else if (!warnedK6Missing) {
          warnedK6Missing = true;
          console.warn("[perf] k6 not on PATH — skipped CLI runs. Install k6 or use executor cli/both after installing.");
        }
      }

      outputs.push({ mode, scriptPath: abs, k6Status });
    } catch (e) {
      console.warn(`[perf] Failed mode ${mode}: ${e.message}`);
      outputs.push({ mode, error: e.message });
    }
  }

  if (executor === "mcp" || executor === "both") {
    const handoffDir = output.mcpHandoffDir || path.join(__dirname, "..", "mcp-handoff");
    const handoffFile = await writeK6Handoff(handoffDir, {
      mcpServerId: performance.k6ServerId,
      mcpCommand: performance.k6Command,
      baseUrl,
      k6EnvRelativePath: k6EnvRel,
      projectRepo,
      scriptDirectory: scriptDirRel,
      primaryScripts,
      mcpRunDefaults,
      mcpRunByMode,
      userStories: perfStories.map(s => ({
        title: s.title,
        type: s.type,
        priority: s.priority,
        description: s.description,
        testFor: s.testFor || ""
      }))
    });
    console.log(
      `[perf] k6 MCP handoff written: ${handoffFile}\n` +
        `  → Modes: ${list.join(", ")} under ${scriptDirRel}/. Local runs: source ${k6EnvRel} (see localK6RunHint in handoff). Cursor: .cursor/rules/mcp-test-orchestration.mdc.`
    );
  }

  return outputs;
}

module.exports = { runPerformanceTestAgent };
